# Generated by Django 3.0.7 on 2020-08-14 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20200814_0403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='product_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.Accessories'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product_l',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.Laptop'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product_m',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.Mobile'),
        ),
    ]
