# Generated by Django 3.0.7 on 2020-08-31 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20200821_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='product_m',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.Mobile'),
        ),
    ]
