# Generated by Django 3.0.7 on 2020-08-31 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20200901_0219'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Accessories',
        ),
        migrations.DeleteModel(
            name='Laptop',
        ),
    ]
